# Generated by Django 5.2.3 on 2025-06-16 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da modalidade (Ex: Judô, Jiu Jitsu.)', max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, help_text='Uma breve descrição da modalidade.', null=True)),
            ],
        ),
    ]
