# Generated by Django 5.2.3 on 2025-06-24 17:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_academia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Plano')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor Mensal')),
                ('duracao_meses', models.IntegerField(default=1, verbose_name='Duração (meses)')),
            ],
        ),
        migrations.AddField(
            model_name='modalidade',
            name='utiliza_faixas',
            field=models.BooleanField(default=False, verbose_name='Utiliza Faixas'),
        ),
        migrations.CreateModel(
            name='Faixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome da Faixa')),
                ('ordem', models.PositiveIntegerField(help_text='Usado para ordenação (ex: Branca=1, Azul=2, etc.)')),
                ('modalidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faixas', to='gestao_academia.modalidade')),
            ],
            options={
                'ordering': ['ordem'],
                'unique_together': {('modalidade', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='E-mail')),
                ('data_matricula', models.DateField(default=django.utils.timezone.now, verbose_name='Data da Matrícula')),
                ('plano', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alunos', to='gestao_academia.plano', verbose_name='Plano Atual')),
            ],
        ),
        migrations.CreateModel(
            name='MatriculaModalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(default=django.utils.timezone.now)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao_academia.aluno')),
                ('faixa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestao_academia.faixa')),
                ('modalidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao_academia.modalidade')),
            ],
            options={
                'unique_together': {('aluno', 'modalidade')},
            },
        ),
    ]
