# Generated by Django 5.2.3 on 2025-06-25 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_academia', '0002_plano_modalidade_utiliza_faixas_faixa_aluno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_alunos/', verbose_name='Foto'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='modalidades',
            field=models.ManyToManyField(related_name='alunos', through='gestao_academia.MatriculaModalidade', to='gestao_academia.modalidade'),
        ),
    ]
