# Generated by Django 5.2.3 on 2025-06-25 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_academia', '0003_aluno_foto_aluno_modalidades'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faixa',
            old_name='name',
            new_name='nome',
        ),
        migrations.AlterField(
            model_name='modalidade',
            name='utiliza_faixas',
            field=models.BooleanField(default=False, verbose_name='Utiliza Faixas?'),
        ),
        migrations.AlterUniqueTogether(
            name='faixa',
            unique_together={('modalidade', 'nome')},
        ),
    ]
