# Generated by Django 5.2.3 on 2025-06-26 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_academia', '0004_rename_name_faixa_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='cpf',
            field=models.CharField(help_text='Formato: 000.000.000-00', max_length=14, null=True, unique=True, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='responsavel',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Responsável (se menor de 18 anos)'),
        ),
    ]
