# Generated by Django 5.2.3 on 2025-06-26 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_academia', '0005_aluno_cpf_aluno_responsavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='cep',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='complemento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='estado',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado (UF)'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='numero',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='rua',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Rua'),
        ),
    ]
