# Generated by Django 5.2.3 on 2025-06-27 12:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_academia', '0006_aluno_bairro_aluno_cep_aluno_cidade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor Pago')),
                ('data_pagamento', models.DateField(default=django.utils.timezone.now, verbose_name='Data do Pagamento')),
                ('mes_referencia', models.DateField(verbose_name='Mês de Referêrencia')),
                ('forma_pagamento', models.CharField(choices=[('PIX', 'PIX'), ('DIN', 'Dinheiro'), ('CC', 'Cartão de Crédito'), ('CD', 'Cartão de Débito'), ('TRA', 'Transferência Bancária')], max_length=3, verbose_name='Forma de Pagamento')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='gestao_academia.aluno')),
            ],
            options={
                'ordering': ['-data_pagamento', '-mes_referencia'],
            },
        ),
    ]
