# Generated by Django 4.2.11 on 2025-07-01 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_academia', '0007_pagamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Instrutor')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True, verbose_name='E-mail')),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_da_semana', models.IntegerField(choices=[(1, 'Segunda-Feira'), (2, 'Terça-Feira'), (3, 'Quarta-Feira'), (4, 'Quinta-Feira'), (5, 'Sexta-Feira'), (6, 'Sabado'), (7, 'Domingo')], verbose_name='Dia da Semana')),
                ('horario_inicio', models.TimeField(verbose_name='Horário  de Início')),
                ('horario_fim', models.TimeField(verbose_name='Horário Fim')),
                ('max_alunos', models.PositiveIntegerField(verbose_name='Máximo de Alunos')),
                ('instrutor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turmas', to='gestao_academia.instrutor')),
                ('modalidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmas', to='gestao_academia.modalidade')),
            ],
        ),
    ]
