# Generated by Django 4.2.11 on 2025-07-10 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_academia', '0008_instrutor_turma'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='turma',
            options={'ordering': ['dia_da_semana', 'horario_inicio'], 'verbose_name': 'Turma / Horário', 'verbose_name_plural': 'Turmas / Horários'},
        ),
        migrations.AddField(
            model_name='matriculamodalidade',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestao_academia.turma', verbose_name='Turma/Horário'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='cpf',
            field=models.CharField(blank=True, help_text='Formato: 000.000.000-00', max_length=14, null=True, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='modalidade',
            name='nome',
            field=models.CharField(help_text='Nome da modalidade (ex: Musculação, Pilates, Jiu-Jitsu)', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='mes_referencia',
            field=models.DateField(verbose_name='Mês de Referência'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='dia_da_semana',
            field=models.IntegerField(choices=[(1, 'Segunda-feira'), (2, 'Terça-feira'), (3, 'Quarta-feira'), (4, 'Quinta-feira'), (5, 'Sexta-feira'), (6, 'Sábado'), (7, 'Domingo')], verbose_name='Dia da Semana'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='horario_fim',
            field=models.TimeField(verbose_name='Horário de Fim'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='horario_inicio',
            field=models.TimeField(verbose_name='Horário de Início'),
        ),
    ]
